### ISSUE TITLE
What plugin is this? Is this an anti-cheat plugin? Why not release it?

### ISSUE THREAD

**Issue by Hex4gonForc3** [Soof4/TheObserver#1]

**Comment by LiteralSoofa** [comment]
It shows a message in chat if someone has an absurd amount of items. I'll upload a release when I fix a few things.

**Comment by Hex4gonForc3** [comment]
oh, like detecting too many items, for example the number of items is 99999 due to duplicates or cheat item stacks

**Comment by LiteralSoofa** [comment]
yeah

**Comment by Hex4gonForc3** [comment]
bro, can you also make it so that items with a total of 255 can be displayed in the chat, because most mobile players use the duplicate item or stack item cheat,Usually, if you duplicate or stack items once, the number is usually 255, and they keep doing it like that until there are a lot of items.

**Comment by LiteralSoofa** [comment]
I'll look into it when I get some free time

**Comment by Hex4gonForc3** [comment]
Okey👍
