### ISSUE TITLE
good it's been released

### ISSUE THREAD

**Issue by Hex4gonForc3** [Soof4/TheObserver#2]

**Comment by Hex4gonForc3** [comment]
![Uploading IMG_20240322_165409.jpg…]()

**Comment by Hex4gonForc3** [comment]
![Screenshot_2024-03-22-16-19-51-06](https://github.com/Soof4/TheObserver/assets/153827257/89945076-2a8d-439e-9d33-87dfdbdb9861)
I also tried to pick up the item that dropped with the amount 9999, and after I picked it up there was no item observer detection notification in the chat

**Comment by Hex4gonForc3** [comment]
![Uploading Screenshot_2024-03-22-16-21-23-67.jpg…]()

**Comment by Hex4gonForc3** [comment]
![IMG_20240322_165409](https://github.com/Soof4/TheObserver/assets/153827257/10b0c9a9-b92a-4d24-aa7a-d647cf2921dc)
.

**Comment by LiteralSoofa** [comment]
😊
