### ISSUE TITLE
I tried to pick up the item that dropped in the amount of 9999 then I picked it up and detected that the observer item wasn't there, it didn't appear in the chat

### ISSUE THREAD

**Issue by Hex4gonForc3** [Soof4/TheObserver#3]
![Screenshot_2024-03-22-16-19-51-06](https://github.com/Soof4/TheObserver/assets/153827257/10efae4b-39d9-43f9-bd6d-328c59809a24)
![Screenshot_2024-03-22-16-21-23-67](https://github.com/Soof4/TheObserver/assets/153827257/d6e8cf54-0bd3-4524-bd23-42bba5b38159)
![Screenshot_2024-03-22-16-20-39-75](https://github.com/Soof4/TheObserver/assets/153827257/496642a5-dadc-4a92-b7c2-1efa2ab361a0)
Item detection does not appear

**Comment by LiteralSoofa** [comment]
Hmmm, might be because of the item's rarity. Campfires and statues are white rarity which means they have less value for the observer's value calculation.
