### ISSUE TITLE
Bro, can you add item detection with the number 255 too because that is a stack cheat, duplicate item which is also what most mobile players use

### ISSUE THREAD

**Issue by Hex4gonForc3** [Soof4/TheObserver#4]
![IMG_20240322_163102](https://github.com/Soof4/TheObserver/assets/153827257/4b0e2bd3-82a2-497d-aa7f-5b15eef06c99)
That's what the cheat looks like

**Comment by LiteralSoofa** [comment]
I'll look into it

**Comment by LiteralSoofa** [comment]
Improved catching of this dupe with v0.1.5
