### ISSUE TITLE
nice bro, you have made a detection for items with a total of 255, but I have tried it and it is not detected, I have tried using the duplicate item 255 cheat, but the item is not detected

### ISSUE THREAD

**Issue by Hexagonforce12** [Soof4/TheObserver#5]
![IMG_20240420_031911](https://github.com/Soof4/TheObserver/assets/109804725/843cb657-dd8e-4021-aa05-3becb17dc522)
![IMG_20240420_031843](https://github.com/Soof4/TheObserver/assets/109804725/356b0ea5-04be-4eeb-a815-2652fd75251b)

**Comment by LiteralSoofa** [comment]
Ahhh.. I'll try to do a few things to make it work better. But keep your expectations low because it's hard to detect those things :(

**Comment by Hexagonforce12** [comment]
Don't give up bro,You definitely can,you can improve the plugin at any time, I'm not forcing you, I'm giving advice
