### ISSUE TITLE
why some items are not detected? it might be better if all items could be detected

### ISSUE THREAD

**Issue by Hexagonforce12** [Soof4/TheObserver#6]
![IMG_20240425_021548](https://github.com/Soof4/TheObserver/assets/109804725/eeb3e3e6-ee8b-45f9-b475-c97daf611311)

**Comment by LiteralSoofa** [comment]
The way TheObserver works is by calculating a slot value with formula ``item_stack * |item_rarity|`` and then compare this with progress limit which is calculated as `` 2500 * boss_factor``. boss_factor in the formula can be reduced/increased with ``/rate`` command. The whole idea kinda works like a single-layer perceptron **but manual**. 

So, long story short: execute ``/rate 10`` many times, and then will start detecting those items as well.

**Comment by Hexagonforce12** [comment]
ohh like that
